FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libgoogle-glog-dev \
    libgflags-dev \
    libeigen3-dev \
    libopencv-dev \
    libyaml-cpp-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --recursive https://github.com/ceres-solver/ceres-solver.git /ceres-solver
WORKDIR /ceres-solver
RUN git submodule update --init --recursive

RUN mkdir build &&\
    cd build &&\
    cmake .. &&\
    make -j$(nproc) &&\
    make install

WORKDIR /workspace

CMD ["/bin/bash"]
